[package]
name = "thread-pool"
version = "0.1.0"
authors = ["PanSzczerba <26200369+PanSzczerba@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
